name: 'Upload Artefacts Action'
description: 'Upload built artefacts of railmapgen projects to uat-railmapgen/rmg-repositories'
inputs:
  app_name:
    required: true
  version:
    required: true
  dist:
    required: true
  token:
    required: true
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Upload
      run: ${{ github.action_path }}/upload.sh
      shell: bash
      env:
        APP_NAME: ${{ inputs.app_name }}
        VERSION: ${{ inputs.version }}
        DIST: ${{ inputs.dist }}
        TOKEN: ${{ inputs.token }}
